{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "judge-ai-proxy.fullname" . }}
  labels:
    {{- include "judge-ai-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.key }}: {{ .Values.secret.apiKey | b64enc | quote }}
{{- end }}