apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tsa.config" . }}
{{ include "tsa.namespace" . | indent 2 }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
data:
  {{- if (eq .Values.server.args.signer "tink") }}
  chain.pem: {{ required "Tink PEM-encoded certificate chain is required" .Values.server.args.cert_chain | quote }}
  tink.keyset.enc: {{ required "Tink authentication token for Hashicorp Vault API is required" .Values.server.args.tink_enc_keyset | quote }}
  {{- end }}
  {{- if (eq .Values.server.args.signer "kms") }}
  chain.pem: {{ required "KMS PEM-encoded certificate chain is required" .Values.server.args.cert_chain | quote }}
  {{- end }}
  {{- if (eq .Values.server.args.signer "file") }}
  {{- if .Values.server.args.cert_chain }}
  chain.pem: {{ .Values.server.args.cert_chain | quote }}
  {{- else }}
  # Certificate chain will be mounted from secret in vault mode
  # Placeholder - actual chain comes from ExternalSecret pki secret
  chain.pem: ""
  {{- end }}
  {{- end }}
  {{- if and .Values.server.args.creds (ne .Values.server.args.creds "") }}
  cloud_credentials: {{ .Values.server.args.creds | quote }}
  {{- end }}
