apiVersion: v1
kind: Service
metadata:
{{- if .Values.server.service.annotations }}
  annotations:
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
  name: {{ template "tsa.fullname" . }}
{{ include "tsa.namespace" . | indent 2 }}
spec:
  ports:
    {{- tpl (toYaml .Values.server.service.ports) . | nindent 4 }}
  selector:
    {{- include "tsa.selectorLabels" . | nindent 4 }}
  type: "{{ .Values.server.service.type }}"
