apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tsa.serviceAccountName" . }}
{{ include "tsa.namespace" . | indent 2 }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.server.serviceAccount.annotations | indent 4 }}
