{{- if .Values.oidcGithub.enabled }}
{{- if .Values.oidcGithub.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "judge-api.oidcGithubSecret.name" . }}
  labels:
    {{- include "judge-api.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "judge-api.oidcGithubSecret.clientIdKey" . }}: {{ .Values.oidcGithub.clientId | b64enc | quote }}
  {{ include "judge-api.oidcGithubSecret.privateKeyKey" . }}: {{ .Values.oidcGithub.privateKey | b64enc | quote }}
{{- end }}
{{- end }}