{{- if .Values.global.secrets.manual }}
{{- if or .Values.global.secrets.manual.judgeApi.secretName .Values.global.secrets.manual.archivista.secretName .Values.global.secrets.manual.kratos.secretName }}
# This ConfigMap documents manual secret configuration
# It also ensures global.secrets.manual values are accessible to subcharts
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-manual-secrets-config
  labels:
    app.kubernetes.io/name: manual-secrets-config
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  description: "Manual secret configuration for Judge platform services"
  {{- if .Values.global.secrets.manual.judgeApi.secretName }}
  judge-api-secret: {{ .Values.global.secrets.manual.judgeApi.secretName | quote }}
  {{- end }}
  {{- if .Values.global.secrets.manual.judgeApi.secretKey }}
  judge-api-key: {{ .Values.global.secrets.manual.judgeApi.secretKey | quote }}
  {{- end }}
  {{- if .Values.global.secrets.manual.archivista.secretName }}
  archivista-secret: {{ .Values.global.secrets.manual.archivista.secretName | quote }}
  {{- end }}
  {{- if .Values.global.secrets.manual.archivista.secretKey }}
  archivista-key: {{ .Values.global.secrets.manual.archivista.secretKey | quote }}
  {{- end }}
  {{- if .Values.global.secrets.manual.kratos.secretName }}
  kratos-secret: {{ .Values.global.secrets.manual.kratos.secretName | quote }}
  {{- end }}
{{- end }}
{{- end }}