{{- $previewRouterEnabled := false }}
{{- if hasKey .Values "preview-router" }}
  {{- if index .Values "preview-router" "enabled" }}
    {{- $previewRouterEnabled = true }}
  {{- end }}
{{- end }}
{{- if and .Values.global.istio.enabled $previewRouterEnabled }}
---
# Certificate for preview subdomain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: preview-wildcard-tls
  namespace: istio-system
  labels:
    {{- include "judge.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: preview-wildcard-tls
  issuerRef:
    name: {{ .Values.global.istio.tlsIssuer | default "letsencrypt-prod" }}
    kind: ClusterIssuer
  dnsNames:
    - "*.preview.{{ .Values.global.domain }}"
  # DNS-01 challenge required for wildcard certificates
  {{- if .Values.global.istio.tlsDNS01 }}
  acme:
    solvers:
    - dns01:
        route53:
          region: {{ .Values.global.aws.region | default "us-east-1" }}
          {{- if .Values.global.istio.hostedZoneID }}
          hostedZoneID: {{ .Values.global.istio.hostedZoneID }}
          {{- end }}
  {{- end }}
{{- end }}