{{- if .Values.global.secrets.provider }}
{{- if eq .Values.global.secrets.provider "vault" }}
---
# SecretStore for Kratos
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kratos
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "judge.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.global.secrets.vault.server | quote }}
      path: {{ .Values.global.secrets.vault.path | default "secret" | quote }}
      version: {{ .Values.global.secrets.vault.version | default "v2" | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.global.secrets.vault.authMountPath | default "kubernetes" | quote }}
          role: {{ .Values.kratos.vault.role | default "kratos" | quote }}
          serviceAccountRef:
            name: {{ include "kratos.serviceAccountName" . }}
---
# SecretStore for Judge API
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-judge-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "judge.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.global.secrets.vault.server | quote }}
      path: {{ .Values.global.secrets.vault.path | default "secret" | quote }}
      version: {{ .Values.global.secrets.vault.version | default "v2" | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.global.secrets.vault.authMountPath | default "kubernetes" | quote }}
          role: {{ index .Values "judge-api" "vault" "role" | default "judge-api" | quote }}
          serviceAccountRef:
            name: {{ index .Values "judge-api" "serviceAccount" "name" | default "judge-api" | quote }}
---
# SecretStore for Archivista
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-archivista
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "judge.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.global.secrets.vault.server | quote }}
      path: {{ .Values.global.secrets.vault.path | default "secret" | quote }}
      version: {{ .Values.global.secrets.vault.version | default "v2" | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.global.secrets.vault.authMountPath | default "kubernetes" | quote }}
          role: {{ .Values.archivista.vault.role | default "archivista" | quote }}
          serviceAccountRef:
            name: {{ .Values.archivista.serviceAccount.name | default "archivista" | quote }}
{{- end }}
{{- end }}
