{{- if .Values.global.secrets.provider }}
{{- if eq .Values.global.secrets.provider "vault" }}
{{- $kratosServiceAccount := .Values.kratos.serviceAccount.name }}
{{- if not $kratosServiceAccount }}
  {{- if .Values.kratos.serviceAccount.create }}
    {{- $kratosServiceAccount = printf "%s-kratos" .Release.Name }}
  {{- else }}
    {{- $kratosServiceAccount = "kratos" }}
  {{- end }}
{{- end }}
{{- $judgeApiServiceAccount := (index .Values "judge-api").serviceAccount.name }}
{{- if not $judgeApiServiceAccount }}
  {{- if (index .Values "judge-api").serviceAccount.create }}
    {{- $judgeApiServiceAccount = printf "%s-judge-api" .Release.Name }}
  {{- else }}
    {{- $judgeApiServiceAccount = "judge-api" }}
  {{- end }}
{{- end }}
{{- $archivistaServiceAccount := .Values.archivista.serviceAccount.name }}
{{- if not $archivistaServiceAccount }}
  {{- if .Values.archivista.serviceAccount.create }}
    {{- $archivistaServiceAccount = printf "%s-judge-archivista" .Release.Name }}
  {{- else }}
    {{- $archivistaServiceAccount = "archivista" }}
  {{- end }}
{{- end }}
---
# SecretStore for Kratos
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kratos
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "judge.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.global.secrets.vault.server | quote }}
      path: {{ .Values.global.secrets.vault.path | default "secret" | quote }}
      version: {{ .Values.global.secrets.vault.version | default "v2" | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.global.secrets.vault.authMountPath | default "kubernetes" | quote }}
          role: {{ .Values.kratos.vault.role | default "kratos" | quote }}
          serviceAccountRef:
            name: {{ $kratosServiceAccount | quote }}
---
# SecretStore for Judge API
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-judge-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "judge.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.global.secrets.vault.server | quote }}
      path: {{ .Values.global.secrets.vault.path | default "secret" | quote }}
      version: {{ .Values.global.secrets.vault.version | default "v2" | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.global.secrets.vault.authMountPath | default "kubernetes" | quote }}
          role: {{ index .Values "judge-api" "vault" "role" | default "judge-api" | quote }}
          serviceAccountRef:
            name: {{ $judgeApiServiceAccount | quote }}
---
# SecretStore for Archivista
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-archivista
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "judge.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.global.secrets.vault.server | quote }}
      path: {{ .Values.global.secrets.vault.path | default "secret" | quote }}
      version: {{ .Values.global.secrets.vault.version | default "v2" | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.global.secrets.vault.authMountPath | default "kubernetes" | quote }}
          role: {{ .Values.archivista.vault.role | default "archivista" | quote }}
          serviceAccountRef:
            name: {{ $archivistaServiceAccount | quote }}
{{- end }}
{{- end }}
