apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-judge-api
  labels:
    helm.sh/chart: judge-api-1.6.11
    app.kubernetes.io/name: judge-api
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::831646886084:role/prod-judge-judge-api
