
---
# SecretStore for Kratos
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kratos
  namespace: NAMESPACE
  labels:
    helm.sh/chart: judge-chart-1.7.89
    app.kubernetes.io/name: judge
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.6.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "kratos"
          serviceAccountRef:
            name: "RELEASE-NAME-judge-kratos"
---
# SecretStore for Judge API
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-judge-api
  namespace: NAMESPACE
  labels:
    helm.sh/chart: judge-chart-1.7.89
    app.kubernetes.io/name: judge
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.6.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "judge-api"
          serviceAccountRef:
            name: "custom-judge-api-sa"
---
# SecretStore for Archivista
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-archivista
  namespace: NAMESPACE
  labels:
    helm.sh/chart: judge-chart-1.7.89
    app.kubernetes.io/name: judge
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "1.6.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "https://vault.example.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "archivista"
          serviceAccountRef:
            name: "RELEASE-NAME-judge-archivista"
