{{- if .Values.deployment.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kratos.serviceAccountName" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "kratos.labels" . | nindent 4 }}
  {{- if or .Values.deployment.serviceAccount.annotations (and .Values.global (hasKey .Values.global "aws") .Values.global.aws (hasKey .Values.global.aws "irsa") .Values.global.aws.irsa (hasKey .Values.global.aws.irsa "enabled") .Values.global.aws.irsa.enabled) }}
  annotations:
    {{- include "judge.aws.irsa.annotations" (dict "service" "kratos" "root" .) | nindent 4 }}
    {{- with .Values.deployment.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
