{{- if and (not .Values.secret.enabled) .Values.global.dev }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kratos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kratos.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  dsn: "postgresql://{{ .Values.global.devDatabase.username }}:{{ .Values.global.devDatabase.password }}@{{ .Release.Name }}-postgresql:5432/kratos?sslmode=disable"
  secretsCookie: "PLEASE-CHANGE-ME-IM-NOT-VERY-SECURE-IN-DEV"
  secretsCipher: "32-BYTE-SECRET-FOR-DEV-USE-ONLY!!"
  oidcGithubClientId: "dev-mode-placeholder-client-id"
  oidcGithubClientSecret: "dev-mode-placeholder-secret"
{{- end }}
