{{- if (include "fulcio.createcertsEnabled" . | eq "true") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fulcio.createcerts.fullname" . }}
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
  {{- $argocdAnnotations := include "judge.argocd.jobAnnotations" . }}
  {{- if or $argocdAnnotations .Values.createcerts.annotations }}
  annotations:
    {{- if $argocdAnnotations }}
    {{- $argocdAnnotations | nindent 4 }}
    {{- end }}
    {{- with .Values.createcerts.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
{{- if .Values.createcerts.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.createcerts.ttlSecondsAfterFinished }}
{{- end }}
  template:
    metadata:
      labels:
        {{- include "fulcio.labels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ template "fulcio.serviceAccountName.createcerts" . }}
      restartPolicy: Never
      automountServiceAccountToken: {{ .Values.createcerts.serviceAccount.mountToken }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ template "fulcio.createcerts.fullname" . }}
          image: "{{ template "fulcio.image" .Values.createcerts.image }}"
          imagePullPolicy: "{{ .Values.createcerts.image.pullPolicy }}"
          args: ["--secret={{ .Values.server.secret }}"]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
    {{- if .Values.createcerts.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.createcerts.containerSecurityContext | indent 12 }}
    {{- end }}
    {{- if .Values.createcerts.securityContext }}
      securityContext:
{{ toYaml .Values.createcerts.securityContext | indent 8 }}
    {{- end }}
{{- end }}
