{{- range .Values.server.ingresses }}
{{- if and (.enabled) (eq .className "gce") (.backendConfigSpec) }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ template "fulcio.fullname" $ -}}-{{- .name }}
  labels:
    {{- include "fulcio.labels" $ | nindent 4 }}
{{ include "fulcio.namespace" $ | indent 2 }}
spec:
{{ toYaml .backendConfigSpec | indent 2 }}
---
{{- end }}
{{- end }}