apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fulcio.serviceAccountName" . }}
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.server.serviceAccount.annotations | indent 4 }}
