apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fulcio.config" . }}
{{ include "fulcio.namespace" . | indent 2 }}
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
data:
  {{- if .Values.config.contents }}
  {{/* Backward compatibility: old JSON format */}}
  config.json: |-
{{ include "fulcio.configmap.contents" . | indent 4 }}
  {{- else }}
  {{/* New YAML format */}}
  config.yaml: |-
{{ include "fulcio.configmap.contents" . | indent 4 }}
  {{- end }}
  {{- if (eq .Values.server.args.certificateAuthority "kmsca")}}
  chain.pem: {{.Values.server.args.kms_cert_chain | quote }}
  {{- end }}
