{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  {{- if .Values.namespace.labels }}
  labels:
    {{- .Values.namespace.labels | toYaml | nindent 4 }}
  {{- end }}
{{- end }}