apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-localstack
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: localstack
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 4566
    protocol: TCP
    name: edge
  selector:
    app: localstack
    release: {{ .Release.Name }}
