{{- $usingVault := and .Values.global .Values.global.secrets (eq .Values.global.secrets.provider "vault") -}}
{{- if and $usingVault (not .Values.global.dev) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "kratos-selfservice-ui-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kratos-selfservice-ui-node.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kratos
    kind: SecretStore
  target:
    name: {{ include "kratos-selfservice-ui-node.secretname" . }}
    creationPolicy: Owner
  data:
    - secretKey: secretsCookie
      remoteRef:
        key: {{ .Values.global.secrets.vault.env }}/kubernetes/app/{{ .Values.global.secrets.vault.project }}
        property: kratos_ui_secrets_cookie
    - secretKey: secretsCSRFCookie
      remoteRef:
        key: {{ .Values.global.secrets.vault.env }}/kubernetes/app/{{ .Values.global.secrets.vault.project }}
        property: kratos_ui_secrets_csrf_cookie
{{- end }}
