apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos-selfservice-ui-node.fullname" . }}
  labels:
{{ include "kratos-selfservice-ui-node.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.name }}
      {{- if eq .Values.service.type "NodePort" }}
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "kratos-selfservice-ui-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
