apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-judge-archivista
  labels:
    helm.sh/chart: archivista-1.6.11
    app.kubernetes.io/name: judge-archivista
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: "0.1.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::831646886084:role/prod-judge-archivista
