{{- if not .Values.sqlStore.createSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "archivista.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archivista.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-archivista
    kind: SecretStore
  target:
    name: {{ include "archivista.fullname" . }}-database
    creationPolicy: Owner
  data:
    - secretKey: connectionString
      remoteRef:
        key: demo/kubernetes/rds/testifysec-judge
        property: archivista_dsn
{{- end }}
